"""
Seed the PostgreSQL database with doctor data from JSON files.

Reads doctors.json (generated by generate_synthetic.py) and inserts
all records into the doctors table with PostGIS geography points.
"""

import asyncio
import json
from pathlib import Path

from sqlalchemy import text
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession, async_sessionmaker

from app.config import settings
from app.db.models import Base, Doctor

DATA_DIR = Path(__file__).parent.parent / "app" / "data" / "seed"


async def seed_database():
    """Create tables and seed doctor data."""
    engine = create_async_engine(settings.database_url, echo=False)

    # Create tables
    async with engine.begin() as conn:
        # Ensure PostGIS extension exists
        await conn.execute(text("CREATE EXTENSION IF NOT EXISTS postgis"))
        await conn.run_sync(Base.metadata.create_all)

    print("Tables created successfully.")

    # Load doctor data
    doctors_path = DATA_DIR / "doctors.json"
    if not doctors_path.exists():
        print("⚠ No doctors.json found. Run scripts/generate_synthetic.py first.")
        return

    with open(doctors_path, "r", encoding="utf-8") as f:
        doctors_data = json.load(f)

    # Insert doctors
    session_factory = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

    async with session_factory() as session:
        # Check if already seeded
        result = await session.execute(text("SELECT COUNT(*) FROM doctors"))
        count = result.scalar()
        if count > 0:
            print(f"Database already has {count} doctors. Skipping seed.")
            return

        for doc in doctors_data:
            doctor = Doctor(
                name=doc["name"],
                gender=doc.get("gender"),
                specialty=doc["specialty"],
                sub_specialization=doc.get("sub_specialization"),
                years_experience=doc.get("years_experience"),
                board_certifications=doc.get("board_certifications"),
                education=doc.get("education"),
                location=f"SRID=4326;POINT({doc['lng']} {doc['lat']})",
                address=doc.get("address"),
                city=doc.get("city"),
                rating=doc.get("rating"),
                review_count=doc.get("review_count"),
                consultation_fee=doc.get("consultation_fee"),
                insurance_accepted=doc.get("insurance_accepted"),
                languages=doc.get("languages"),
                telehealth_available=doc.get("telehealth_available", False),
                phone=doc.get("phone"),
                website=doc.get("website"),
                hospital_name=doc.get("hospital_name"),
                osm_id=doc.get("osm_id"),
                source=doc.get("source", "synthetic"),
            )
            session.add(doctor)

        await session.commit()
        print(f"Seeded {len(doctors_data)} doctors into the database.")

    # Create spatial index
    async with engine.begin() as conn:
        await conn.execute(text(
            "CREATE INDEX IF NOT EXISTS idx_doctors_location ON doctors USING GIST (location)"
        ))
        await conn.execute(text(
            "CREATE INDEX IF NOT EXISTS idx_doctors_specialty ON doctors (specialty)"
        ))
        await conn.execute(text(
            "CREATE INDEX IF NOT EXISTS idx_doctors_city ON doctors (city)"
        ))
    print("Spatial and attribute indexes created.")

    await engine.dispose()


def main():
    asyncio.run(seed_database())


if __name__ == "__main__":
    main()
